Add GitHub action checking links in .md files
codeforamerica/brigade-project-index pull request #48
Opened 2021-03-24 20:09 UTC by k3KAW8Pnf7mkmdSMPHz27

Adds a check for broken links when .md files are changed.

2021-03-24 22:15 UTC, themightychris commented on .github/workflows/check-links.yml
> +      - '**.md'
maybe scope to `docs/` ?

2021-03-24 22:21 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on .github/workflows/check-links.yml
> +      - '**.md'
`/README.md` and `/docs/` are good. I am not sure about https://github.com/codeforamerica/brigade-project-index/tree/master/crawler given that it does contain broken links at the moment.
There is also an option to only check changed files but I'd not recommend it (i.e., changing the header of a file can break links in other files)

2021-03-24 22:22 UTC, themightychris commented on .github/workflows/check-links.yml
> +      - '**.md'
hmm we should probably fix those links...so maybe let's keep checking all markdown...no broken links are good broken links

2021-03-24 22:32 UTC, k3KAW8Pnf7mkmdSMPHz27 commented
Also, the [latest run on my fork](https://github.com/k3KAW8Pnf7mkmdSMPHz27/brigade-project-index/pull/2/checks?check_run_id=2188623461)

I have started to fix all broken links that are found but it is going to take a will and will be in a different PR.

2021-03-24 22:37 UTC, themightychris commented
@k3KAW8Pnf7mkmdSMPHz27 it would be awesome to have a markdown linter in this workflow (or a separate one?) too

2021-03-24 22:43 UTC, k3KAW8Pnf7mkmdSMPHz27 commented
@themightychris I'll look at adding a linter in the next couple of days (Friday most likely).

2021-03-24 23:00 UTC, k3KAW8Pnf7mkmdSMPHz27 commented
Well, expect an update on Friday,
1. Check `README.md` and `docs/`
2. Exclude some "URLs" that should not work
3. Add linter

2021-03-26 20:41 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on .github/workflows/check-links.yml
> +      - '**.md'
Oups, I am sorry. I somehow missed your comment, I'll revert to this behavior again.

2021-03-26 21:34 UTC, k3KAW8Pnf7mkmdSMPHz27 commented
I added a linter with some default options, but I think there is a need to look over them, see https://github.com/k3KAW8Pnf7mkmdSMPHz27/brigade-project-index/runs/2205386468?check_suite_focus=true for latest run.

2021-03-28 17:34 UTC, k3KAW8Pnf7mkmdSMPHz27 commented
@themightychris I'd argue that the rules are a bit on the strict side, but they are fairly easy to disable so perhaps keep them as is and see how it works out in the long run.

I'll start updating the markdown documents.

2021-04-10 16:44 UTC, k3KAW8Pnf7mkmdSMPHz27 commented
Additionally, disabling these might be a good idea, 

* `MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]`. I don't think this actually does anything.
* `MD034/no-bare-urls Bare URL used`. I prefer `[Meaningful name](http://link)` to bare URLs, but perhaps it shouldn't be checked by the linter.

2021-04-21 22:18 UTC, themightychris commented
I don't see any reason to keep consecutive blank lines around, I always clear those out to shut the linter up

I'd also leave the no-bare-urls rule on, bare URL's can simply be wrapped like `<http://link>` to turn them into links -- full links with meaningful names are ideal but when there isn't one or the content is the URL you can just wrap URLs in angle brackets

2021-04-21 22:20 UTC, themightychris requested changes

2021-04-21 22:20 UTC, themightychris commented on markdown-link-check-configuration.json
> +      "pattern": "^https://github.com/codefornola$"
why is this needed? that URL seems to load

2021-04-21 22:20 UTC, themightychris commented on markdown-link-check-configuration.json
> +      "pattern": "brigade-project-index/settings/secrets"
does this one just fail because it requires being logged in as an admin?

2021-04-21 22:20 UTC, themightychris commented on markdown-linter-configuration.yml
> +default: false # includes/excludes all rules by default
what all did you customize here? I usually just use the default markdownlint config with mkdocs sites, if you had to disable a lot of rules they're probably things we should just fix in the content

2021-04-21 22:23 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on markdown-link-check-configuration.json
> +      "pattern": "brigade-project-index/settings/secrets"
I'd guess so.

2021-04-21 23:09 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on markdown-linter-configuration.yml
> +default: false # includes/excludes all rules by default
E.g., [rule 13](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md013---line-length) will be set to false, and I don't really see the point of enforcing it.

I view the purpose of the mkdoc generated page as an easy enough way for anyone to go in and make changes. If all the markdown rules are enforced with their default options, there will be quite a few warnings whenever someone not familiar with markdown makes changes. It is not a problem per se, but that is why I disable rules that don't necessarily add that much value and are likely to be validated.

I can set them all to true or switch to markdownlint/alternative configuration if you want.

2021-04-21 23:10 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on markdown-link-check-configuration.json
> +      "pattern": "^https://github.com/codefornola$"
Apparently no reason 🤦

2021-04-21 23:15 UTC, k3KAW8Pnf7mkmdSMPHz27 commented on markdown-link-check-configuration.json
> +      "pattern": "brigade-project-index/settings/secrets"
It exists if you have the right access if that is what you are asking 😛 
There might be a point to not ignoring it, having a clickable link that only some people can use is not necessarily the best idea.

2021-05-06 00:11 UTC, themightychris commented on markdown-link-check-configuration.json
> +      "pattern": "brigade-project-index/settings/secrets"
I think ignoring it makes sense. We can document the system publically even if the public won't have access to every resource. If someone came around years from now after we're all gone and wanted to update things they'd be able to figure out what access to request from who from that information

2021-05-06 00:14 UTC, themightychris commented on markdown-linter-configuration.yml
> +default: false # includes/excludes all rules by default
I find it's best to stick to the default configuration as closely as possible, since a lot of editors with built-in linting will be following that same standard. It is better that contributors be mildly annoyed by the strict linter, than for built-in linting in editors to be useless because they're highlighting so many rules that we're ignoring. When the starting point for any contributor is that their editor will show zero errors or warnings when they open our markdown files, the warnings/errors that come up while they work will be easier to notice and deal with

2021-05-06 00:14 UTC, merged

2021-05-06 00:29 UTC, themightychris commented on markdown-linter-configuration.yml
> +default: false # includes/excludes all rules by default
@k3KAW8Pnf7mkmdSMPHz27 I went ahead and merged this so we could see it in action, and created #53 as a followup